### ISSUE TITLE
Error in synchronization of 'sample.1.prop' with 'taxa.1.prop' 

### ISSUE THREAD

**Issue by haseebmanzur** [mengyu-he/MIDASim#6]
I have received a revision to my manuscript to synthesize the microbiome data through a microbiome-based simulator, and I find your tool useful. Since I have a few days left for submission I am continuously facing one error again and again after trying various ways. The error screenshot is attached along with the input. I am reaching out for your help so I can submit my paper asap. I'll be grateful.

I am also pasting the code I have been using below:

# Load necessary libraries
library(MIDASim)
library(readr)
library(scam)

# Load the real data
real_data_path <- "D:/Haseeb_ML/MIDA-SIM/Inputs/Species/Premenopause_Control_Abundance_Matrix.csv"
otu.tab <- read_csv(real_data_path)

# Remove the first column (assuming it contains sample names)
otu.tab <- otu.tab[, -1]

# Set up the MIDASim model in nonparametric mode
count.ibd.setup <- MIDASim.setup(otu.tab, mode = 'nonparametric', n.break.ties = 10)

# Simulate new data (1000 samples) based on the real data
n_samples <- 1000
new.lib.size <- sample(1000:10000, size = n_samples, replace = TRUE)

# Fit the Shape Constrained Additive Model (SCAM) to adjust non-zero counts
obs.sample.1.ct <- rowSums(otu.tab > 0)  # Number of non-zero counts per sample
xvar <- log10(rowSums(otu.tab))          # Log of total counts per sample
scamfit.non0 <- scam::scam(log10(obs.sample.1.ct) ~ s(xvar, bs = "mpi"))

# Predict the new number of non-zero cells for the simulated samples
sample.1.ct <- 10^(predict(scamfit.non0, newdata = data.frame(xvar = log10(new.lib.size))))

# Calculate the number of samples and taxa
n.samples <- nrow(otu.tab)  # Original number of samples
n.taxa <- ncol(otu.tab)     # Original number of taxa

# Step 1: Calculate sample proportions based on non-zero counts for each sample
new.sample.1.prop <- sample.1.ct / n.taxa  # Proportion of non-zero taxa per sample

# Step 2: Calculate taxa proportions based on non-zero counts for each taxon
obs.taxa.1.ct <- colSums(otu.tab > 0)  # Observed number of non-zero counts per taxon
new.taxa.1.prop <- obs.taxa.1.ct / n.samples  # Proportion of non-zero samples per taxon

# Step 3: Synchronize the proportions
# Calculate total sums of sample and taxa proportions
total_sample_prop <- sum(new.sample.1.prop)
total_taxa_prop <- sum(new.taxa.1.prop)

# Direct adjustment for synchronization
if (total_sample_prop * n.taxa != total_taxa_prop * n.samples) {
  adjustment_factor <- (total_sample_prop * n.taxa) / (total_taxa_prop * n.samples)
  new.taxa.1.prop <- new.taxa.1.prop * adjustment_factor
}

# Final validation
sample_total <- sum(new.sample.1.prop) * n.taxa
taxa_total <- sum(new.taxa.1.prop) * n.samples

if (abs(sample_total - taxa_total) > 1e-5) {
  stop("Synchronization failed after direct adjustment.")
}

# Proceed with MIDASim.modify
count.ibd.modified <- MIDASim.modify(
  count.ibd.setup,
  lib.size = new.lib.size,
  sample.1.prop = new.sample.1.prop,
  taxa.1.prop = new.taxa.1.prop
)

# Step 5: Generate the simulated data
simulated.data <- MIDASim(count.ibd.modified)

# Step 6: Check the summary of the simulated data
summary(simulated.data)

# Step 7: Save the simulated data
# Write the simulated count data (sim_count) to CSV
write_csv(simulated.data$sim_count, 
          "D:/Haseeb_ML/MIDA-SIM/Inputs/Species/Simulated_Premenopause_Control_1000_Samples_Count.csv")

# Write the simulated relative abundances (sim_rel) to CSV
write_csv(simulated.data$sim_rel, 
          "D:/Haseeb_ML/MIDA-SIM/Inputs/Species/Simulated_Premenopause_Control_1000_Samples_Abundance.csv")

# Step 8: Check the first few rows of simulated count data
head(simulated.data$sim_count)

[Premenopause_Control_Abundance_Matrix.csv](https://github.com/user-attachments/files/17957598/Premenopause_Control_Abundance_Matrix.csv)
![midasim_error](https://github.com/user-attachments/assets/09e216cc-0281-4ceb-9614-76de95fcdbb8)

**Comment by mengyu-he** [comment]
Hi Haseeb,

Thank you for reaching out. Since you are modifying the fitted model (change library size and proportion of 1's), I highly recommend you using the parametric mode of the function.

To resolve the error, please consider the following two corrections to your code:

**1) change MIDASim mode**. When setting up the model, use parametric mode as follows,

`count.ibd.setup <- MIDASim.setup(otu.tab, mode = 'parametric', n.break.ties = 10)`

**2) change the sample size to 1000 when you modifying model features**. I notice that you are simulating 1000 samples. When synchronizing proportions, you should use `n_samples` (the target sample size, 1000), rather than `n.samples` (the observed sample size, 25). So update all `n.samples` in steps 2 and 3 to `n_samples`.

By making the above two corrections, your code should execute without errors. If you have any further issues, please feel free to reach out.

Best,
Mengyu

**Comment by haseebmanzur** [comment]
Really appreciate your response. 
I have a query that since my goal is to have a data that accurately mimic the original data, wont the 'non parametric' method would be more appropriate as outlined in your 'readme'.

I did run the code with the non parametric method and it generated no errors as you said, but when I visualized it through the comparative distribution plots of real vs simulated data, they seem way too off the road, which does not really help in using the simulated data. Not to mention that my input file had relative abundances in TPM, so I had to transform the output of MIDASim into TPM method so that I can compare the datasets at equal grounds.

I am still looking forward to generate simulated data which accurately mimic the real data. Please guide me in the current situation.

**Comment by mengyu-he** [comment]
Hi Haseeb, 

This is a great question. The nonparametric mode is used for reproducing the observed dataset, while the parametric mode is used for making modifications to data characteristics. If your goal is to reproduce all the characteristics of the original data, there is no need to change the library size. You could try the following

`otu.tab <- otu.tab[, colSums(otu.tab) > 0] # filter out the taxa that are do not present in any sample`
`fitted.setup <- MIDASim.setup(otu.tab, mode = 'nonparametric', n.break.ties = 10)`
`fitted.modified <- MIDASim.modify(fitted.setup)`
`simulated <- MIDASim(fitted.modified)`

By doing so, the simulated data will retain the characteristics of your original data.

However, if you modify the arguments `sample.1.prop` and `taxa.1.prop`, the simulated data will diverge from the observed data because these arguments modify the taxa features.

And if your goal is to generate a dataset with the same taxa characteristics as the original data but with adjusted library sizes, you can scale the simulated relative abundances by the target library sizes afterwards. For example:

`simulated.count <- simulated$sim_rel * new.lib.size`

This will give you counts that match the new library sizes while preserving the taxa features.

Let me know if you have further questions or need clarification!

Best,
Mengyu

**Comment by haseebmanzur** [comment]
Dear Mengyu,

I am grateful for your kind help.

I followed your direction and got almost similar dataset with same size of the original dataset (n=25).

However, to the best of my understanding based on your response that with non parametric mode if I want to generate 1000 samples it wont really mimic the original data settings since the proportion of samples vs taxa features changes. 

But to clarify, this is the actual goal; to generate additional data of 1000 samples highly mimicing the real dataset. Because I am asked to validate my findings from limited sample size on a reasonable sample size for that I need to simulate a reasonable amount of dataset i.e., 1000 samples in the current case. 

Let me know how I can really achieve this but keeping the original data features and distribution intact.

Best regards,
Haseeb Manzoor

**Comment by mengyu-he** [comment]
Hi Haseeb,

There are two ways to achieve this:

1. Use nonparametric mode with a loop: 
You can use a for loop to generate multiple datasets (e.g., 40 iterations to produce 1000 samples). This ensures you get the desired number of simulated samples while maintaining the original data characteristics. The codes would be like,

`simulated.rel <- matrix(nrow = 1000, ncol = ncol(otu.tab))`
`for (k in 1:40) {`
 ` simulated <- MIDASim(fitted.modified)`
`  simulated.rel[(25*(k-1)+1):(25*k),] <- simulated$sim_rel`
`}`

2. Resampling library sizes and using the parametric mode:
First, obtain new.lib.size (a vector of length 1000) by resampling from the observed library sizes:

`new.lib.size <- sample(rowSums(otu.tab), replace = T)`

Then, under the parametric mode of MIDASim, modify the library sizes as follows:

`fitted.setup <- MIDASim.setup(otu.tab, mode = 'parametric', n.break.ties = 10)`
`fitted.modified <- MIDASim.modify(fitted.setup, lib.size = new.lib.size)`
`simulated <- MIDASim(fitted.modified)`

Both approaches allow you to simulate data with the desired library sizes while preserving the original characteristics. I hope this helps.

Best,
Mengyu

**Comment by haseebmanzur** [comment]
Thank you so much Mengyu for all this help. Stay blessed.

**Comment by mengyu-he** [comment]
Thank you! Stay blessed as well
